# Generated by Django 2.2.14 on 2021-05-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
