# Generated by Django 2.2.14 on 2021-05-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_basketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='items',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.BasketItem'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
